#lang scheme

; (define (+ a b)
;   (if (= a 0) 
;       b 
;       (inc (+ (dec a) b))))

; (define (+ a b)
;   (if (= a 0) 
;       b 
;       (+ (dec a) (inc b))))

; Using the substitution model, illustrate the process generated by each
; procedure in evaluating (+ 4 5). Are these processes iterative or recursive?

; Recursive process

; (+ 5 5)
; (inc (+ 4 5))
; (inc (inc (+ 3 5)))
; (inc (inc (inc (inc (+ 2 5))
; (inc (inc (inc (inc (inc (+ 1 5))
; (inc (inc (inc (inc (inc (inc (+ 0 5))
; (inc (inc (inc (inc (inc 5)))))
; (inc (inc (inc (inc 6))))
; (inc (inc (inc 7)))
; (inc (inc 8))
; (inc 9)
; 10