#lang scheme

; (define (+ a b)
;   (if (= a 0) 
;       b 
;       (inc (+ (dec a) b))))

; (define (+ a b)
;   (if (= a 0) 
;       b 
;       (+ (dec a) (inc b))))

; Using the substitution model, illustrate the process generated by each
; procedure in evaluating (+ 4 5). Are these processes iterative or recursive?
