#lang scheme

; Procedure A
; (define (+ a b)
;   (if (= a 0) 
;       b 
;       (inc (+ (dec a) b))))

; Procedure B
; (define (+ a b)
;   (if (= a 0) 
;       b 
;       (+ (dec a) (inc b))))

; Using the substitution model, illustrate the process generated by each
; procedure in evaluating (+ 4 5). Are these processes iterative or recursive?

; Recursive process (Procedure A)

; (+ 5 5)
; (inc (+ 4 5))
; (inc (inc (+ 3 5)))
; (inc (inc (inc (inc (+ 2 5))
; (inc (inc (inc (inc (inc (+ 1 5))
; (inc (inc (inc (inc (inc (inc (+ 0 5))
; (inc (inc (inc (inc (inc 5)))))
; (inc (inc (inc (inc 6))))
; (inc (inc (inc 7)))
; (inc (inc 8))
; (inc 9)
; 10

; Iterative process (Procedure B)

; (+ 5 5)
; (+ 4 6)
; (+ 3 7)
; (+ 2 8)
; (+ 1 9)
; (+ 0 10)
; 10
